version: "2"
services:
  traefik:
    image: traefik
    command: --logLevel=DEBUG --web
    ports:
      - "80:80"
      - "8080:8080"
  updater:
    build: .
    environment:
      DOCKERCLOUD_USER:
      DOCKERCLOUD_APIKEY:
    links:
      - traefik
